// Dedupe findings + render a Code4rena-style markdown report.
import type { AuditReport, Finding, Severity, TargetRepo } from "../types";

const SEV_ORDER: Severity[] = ["High", "Medium", "Low", "QA", "Gas"];
const SEV_TAG: Record<Severity, string> = { High: "H", Medium: "M", Low: "L", QA: "QA", Gas: "G" };

export function dedupe(findings: Finding[]): Finding[] {
  const seen = new Map<string, Finding>();
  for (const f of findings) {
    const key = `${f.file}:${f.lines[0]}:${f.title.toLowerCase().slice(0, 40)}`;
    const prev = seen.get(key);
    // Prefer higher-confidence / analyzer-confirmed duplicate.
    if (!prev || (f.confidence === "high" && prev.confidence !== "high")) seen.set(key, f);
  }
  return [...seen.values()];
}

function summarize(findings: Finding[]): AuditReport["summary"] {
  const s = { High: 0, Medium: 0, Low: 0, QA: 0, Gas: 0 };
  for (const f of findings) s[f.severity]++;
  return s;
}

export function renderMarkdown(repo: TargetRepo, findings: Finding[], toolsRun: string[]): string {
  const sorted = [...findings].sort(
    (a, b) => SEV_ORDER.indexOf(a.severity) - SEV_ORDER.indexOf(b.severity)
  );
  const sum = summarize(findings);
  const lines: string[] = [];
  lines.push(`# Audit Report — ${repo.owner}/${repo.name}`);
  lines.push(`> Generated by **AuditFlow** · ${new Date().toISOString()}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("| Severity | Count |", "|---|---|");
  for (const s of SEV_ORDER) lines.push(`| ${s} | ${sum[s]} |`);
  lines.push("");
  lines.push(`**Scope:** ${repo.contracts.length} contracts · **Framework:** ${repo.framework}`);
  lines.push(`**Tools run:** ${toolsRun.join(", ")}`);
  lines.push("");

  let n = 0;
  let lastSev: Severity | null = null;
  for (const f of sorted) {
    if (f.severity !== lastSev) { lines.push(`\n## ${f.severity} Risk`); lastSev = f.severity; n = 0; }
    n++;
    const code = `[${SEV_TAG[f.severity]}-${String(n).padStart(2, "0")}]`;
    lines.push(`\n### ${code} ${f.title}`);
    lines.push(`**File:** \`${f.file}\` L${f.lines[0]}-${f.lines[1]} · **Found by:** ${f.tool} (${f.confidence})`);
    lines.push(`\n**Impact**\n\n${f.impact}`);
    lines.push(`\n**Description**\n\n${f.description}`);
    if (f.poc) lines.push(`\n**Proof of Concept**\n\n\`\`\`\n${f.poc}\n\`\`\``);
    lines.push(`\n**Recommendation**\n\n${f.recommendation}`);
    if (f.suggestedDiff) lines.push(`\n**Suggested Fix**\n\n\`\`\`diff\n${f.suggestedDiff}\n\`\`\``);
  }
  return lines.join("\n");
}

export function buildReport(
  repo: TargetRepo, raw: Finding[], toolsRun: string[], startedAt: string
): AuditReport {
  const findings = dedupe(raw);
  return {
    repo, findings, summary: summarize(findings), toolsRun, startedAt,
    finishedAt: new Date().toISOString(),
    markdown: renderMarkdown(repo, findings, toolsRun),
  };
}
